globalVariables(c(
  "abbr_parsed",
  "abbr_stem",
  "adj_orig",
  "adj_parsed",
  "col_pos",
  "dict_varname",
  "lower_original_varname",
  "my_minlength",
  "num_st_ind",
  "original_varname",
  "renamed_n",
  "renamed_var",
  "stem",
  "use_bundle",
  "viable_start"
))