---
title: "Variables' Core Categories"
author: "Ross Didenko"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Three categories are specified in the "Core" column in the SDTM domain models:

- A Required variable is any variable that is basic to the identification of a data record (i.e., essential key
variables and a topic variable) or is necessary to make the record meaningful. Required variables must always be
included in the dataset and cannot be null for any record.
- An Expected variable is any variable necessary to make a record useful in the context of a specific domain. Expected
variables may contain some null values, but in most cases will not contain null values for every record. When the
study does not include the data item for an expected variable, however, a null column must still be included in the
dataset, and a comment must be included in the Define-XML document to state that the study does not include the
data item.
- A Permissible variable should be used in an SDTM dataset wherever appropriate. Although domain specification tables
list only some of the Identifier, Timing, and general observation class variables listed in the SDTM, all are
permissible unless specifically restricted in this implementation guide (see Section 2.7, SDTM Variables Not
Allowed in SDTMIG) or by specific domain assumptions.

    - Domain assumptions that say a Permissible variable is "generally not used" do not prohibit use of the variable.
    - If a study includes a data item that would be represented in a Permissible variable, then that variable must be
included in the SDTM dataset, even if null. Indicate no data were available for that variable in the Define-XML
document.
    - If a study did not include a data item that would be represented in a Permissible variable, then that variable
should not be included in the SDTM dataset and should not be declared in the Define-XML document.


Conditionally required variables in ADaM (Cond) - must be included in the dataset in certain circumstances.
